apiVersion: batch/v1
kind: Job
metadata:
  name: pgbench-run
spec:
  template:
    spec:
      containers:
      - name: pgbench
        image: postgres:16
        command: [pgbench]
        args:
        - --client=4
        - --jobs=2
        - --time=300
        env:
          - name: PGHOST
            value: postgres
          - name: PGDATABASE
            valueFrom:
              secretKeyRef:
                name: pg-creds
                key: database
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: pg-creds
                key: username
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-creds
                key: password
      restartPolicy: Never
  backoffLimit: 0
