apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        args:
        - -c
        - synchronous_commit=off
        - -c
        - shared_buffers=512MB
        - -c
        - wal_level=logical
        - -c
        - max_replication_slots=10
        - -c
        - max_wal_senders=10
        - -c
        - checkpoint_timeout=15min
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pg-creds
              key: database
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-creds
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-creds
              key: password
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: 1024Mi
          limits:
            memory: 1536Mi
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
#      storageClassName: "standard" # Change this if you have a specific storage class
      resources:
        requests:
          storage: 250Gi
